apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: ecom-backend
        image: mrmiano/ecom-backend-image:v1.0.0
        imagePullPolicy: Always
        env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo-url
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip-service
spec:
  selector:
    app: ecom-backend
  ports:
  - port: 5000
    targetPort: 5000